# Generated by Django 4.2.2 on 2023-11-14 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='Images')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'VOTING'), ('3', 'ARCHIVE')], default='3', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bubble_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_chat', to='core.bubble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('interests', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('original_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.communitychat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter_small', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BubbleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('1', 'VISIBLE'), ('2', 'NOT_VISIBLE')], default='2', max_length=10)),
                ('bubble_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_registered_name', to='core.bubble')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
