# Generated by Django 4.2.2 on 2023-11-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friend_created_on_alter_bubblemember_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bubblemember',
            name='profile',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(to='core.profiletag'),
        ),
    ]
