# Generated by Django 4.2.2 on 2023-11-15 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_bubblemember_user_id_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bubblemember',
            unique_together={('bubble_id', 'user_id')},
        ),
    ]
