# Generated by Django 4.2.2 on 2023-11-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bubblemember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profil_pics'),
        ),
        migrations.AlterField(
            model_name='bubble',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
