# Generated by Django 4.2.2 on 2023-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_friend_status_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='status',
            new_name='status1',
        ),
        migrations.AddField(
            model_name='friend',
            name='status2',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
