# Generated by Django 4.2.2 on 2023-12-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='EntryTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_entrytest', to='core.entrytest'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_question', to='core.question'),
        ),
        migrations.AddField(
            model_name='optionresponse',
            name='EntryTest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OptionResponce_entrytest', to='core.entrytest'),
        ),
        migrations.AddField(
            model_name='optionresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OptionResponce_question', to='core.question'),
        ),
        migrations.AlterField(
            model_name='optionresponse',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OptionResponce_option', to='core.option'),
        ),
        migrations.AlterField(
            model_name='optionresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
