# Generated by Django 4.2.2 on 2023-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_question_answer_answer_entrytest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytest',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], default='archive', max_length=7),
        ),
    ]
