# Generated by Django 4.2.2 on 2023-12-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_question_choices_messagenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleMessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bubble')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_sender', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
