# Generated by Django 4.0 on 2023-12-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0017_bubblemessagenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytest',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='core.Question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='core.ProfileTag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='Question_option', to='core.Option'),
        ),
        migrations.CreateModel(
            name='EntryTestSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submit', models.BooleanField(default=False)),
                ('entryTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntryTestSubmitEntryTest', to='core.entrytest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EntryTestSubmitUser', to='auth.user')),
            ],
        ),
    ]
