# Generated by Django 4.0 on 2023-12-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_entrytest_questions_alter_profile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bubblemessagenotification',
            name='bubble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_bubble', to='core.bubble'),
        ),
    ]
