# Generated by Django 4.0 on 2023-12-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0019_alter_bubblemessagenotification_bubble'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='BubblePostResponseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_post_response_notificatione_bubble', to='core.bubble')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_post_response_notification_post', to='core.communitychat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_post_response_notification_sender', to='auth.user')),
            ],
        ),
    ]
